name: pruebaslistado
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.22

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0
  photo_view: ^0.13.0
  shared_preferences: ^2.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
    - assets/marismas/
    - assets/fotos/
    - assets/fotos/monitoreo/
    - assets/fotos/sitio/
    - assets/fotos/capacitacion/
    - assets/icons/
    
  uses-material-design: true
